# Generated by Django 6.0 on 2025-12-15 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inloggen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gebruikers',
            name='isSuperuser',
            field=models.BooleanField(default=False),
        ),
    ]
